# Generated by Django 5.2.3 on 2025-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(blank=True, null=True, upload_to='about_img/')),
                ('about_h2', models.CharField(max_length=1000)),
                ('about_p', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog_img/')),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_heading', models.CharField(max_length=400)),
                ('blog_p1', models.CharField(max_length=2000)),
                ('blog_qutous', models.CharField(max_length=2000)),
                ('blog_p2', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('number_of_guests', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('budget_range', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_page', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title_h2', models.CharField(max_length=1000)),
                ('slide_title_p', models.CharField(max_length=1000)),
                ('zoom_img', models.ImageField(blank=True, null=True, upload_to='home_page_img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='home_img_holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_holder1', models.ImageField(blank=True, null=True, upload_to='img_holder/')),
                ('img_holder2', models.ImageField(blank=True, null=True, upload_to='img_holder/')),
                ('img_holder3', models.ImageField(blank=True, null=True, upload_to='img_holder/')),
                ('img_holder4', models.ImageField(blank=True, null=True, upload_to='img_holder/')),
                ('img_holder5', models.ImageField(blank=True, null=True, upload_to='img_holder/')),
                ('img_holder6', models.ImageField(blank=True, null=True, upload_to='img_holder/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_page_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_gallery', models.ImageField(blank=True, null=True, upload_to='home_page_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_plan', models.IntegerField()),
                ('premium_plan', models.IntegerField()),
                ('luxery_plan', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_paragraph', models.CharField(max_length=1000)),
                ('testimonial_img', models.ImageField(blank=True, null=True, upload_to='testimonial_img/')),
                ('testimonial_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='why_choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_choose_img', models.ImageField(blank=True, null=True, upload_to='why_choose_img/')),
                ('why_choose_h2', models.CharField(max_length=1000)),
                ('why_choose_p', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='why_choose_lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
